version: "3.8"
services:
  db:
    image: docker.arvancloud.ir/postgres:15
    container_name: retail_postgres
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_password
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retail_user -d retail_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: docker.abrha.net/dpage/pgadmin4
    container_name: retail_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
